language: node_js
node_js:
  - 0.10
before_install: npm install -g grunt-cli
script: grunt test
before_script:
  - chmod +x ./public/js/modules/git/getlogs.sh
  - mkdir ./work
  - chmod +w ./work
after_script:
  - ls ./work
  - pwd